version: '3.2'

services:
  define-me:
    container_name: define-me
    build: .
    expose:
      - 5000
    environment:
      - HOST=0.0.0.0
    ports:
      - 8081:8080
    command: npm start & wait-on http://localhost:8081 & wait-on http://localhost:8080

  cypress:
    container_name: cypress
    image: "cypress/browsers:node14.19.0-chrome100-ff99-edge"
    volumes:
     - ./cypress:/cypress
    command: npx cypress run